/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package irondeer;

import java.util.Calendar;
import java.util.Date;

/**
 *
 * @author mtblock
 */
public class GUI_1 extends javax.swing.JFrame implements Runnable {
    boolean pressed=false;
    linkPrintBalance stub=new linkPrintBalance();
    /**
     * Creates new form GUI_1
     */
    public GUI_1() {
        initComponents();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        Settimana = new javax.swing.JPanel();
        Mon = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Vaschetta = new javax.swing.JButton();
        Stampa = new javax.swing.JButton();
        Cliente = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        AddNewLine = new javax.swing.JPanel();
        Tara1 = new javax.swing.JButton();
        Tue = new javax.swing.JPanel();
        Wed = new javax.swing.JPanel();
        Thu = new javax.swing.JPanel();
        Fri = new javax.swing.JPanel();
        Sat = new javax.swing.JPanel();
        Sun = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout SettimanaLayout = new javax.swing.GroupLayout(Settimana);
        Settimana.setLayout(SettimanaLayout);
        SettimanaLayout.setHorizontalGroup(
            SettimanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 932, Short.MAX_VALUE)
        );
        SettimanaLayout.setVerticalGroup(
            SettimanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 541, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Settimana", Settimana);

        jScrollPane1.setViewportView(jTree1);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome Prodotto", "Ora di Consegna", "+", "Q.tà", "-", "Extra", "PerSempre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Float.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LineOrderPressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                LineOrderReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LineOrderClick(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
        }

        Vaschetta.setText("Tara");
        Vaschetta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VaschettaActionPerformed(evt);
            }
        });

        Stampa.setText("jButton1");
        Stampa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StampaActionPerformed(evt);
            }
        });

        jLabel2.setText("Cliente");

        jTextField2.setText("Nome fighissimo");

        jTextField3.setEditable(false);
        jTextField3.setText("6:00");

        jLabel3.setText("Orario Consegna");

        jTextField4.setEditable(false);
        jTextField4.setText("18:00:15");

        jTextField5.setEditable(false);
        jTextField5.setText("+5");

        javax.swing.GroupLayout ClienteLayout = new javax.swing.GroupLayout(Cliente);
        Cliente.setLayout(ClienteLayout);
        ClienteLayout.setHorizontalGroup(
            ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClienteLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(3, 3, 3)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        ClienteLayout.setVerticalGroup(
            ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClienteLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout AddNewLineLayout = new javax.swing.GroupLayout(AddNewLine);
        AddNewLine.setLayout(AddNewLineLayout);
        AddNewLineLayout.setHorizontalGroup(
            AddNewLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        AddNewLineLayout.setVerticalGroup(
            AddNewLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        Tara1.setText("Tara");
        Tara1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tara1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MonLayout = new javax.swing.GroupLayout(Mon);
        Mon.setLayout(MonLayout);
        MonLayout.setHorizontalGroup(
            MonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MonLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(MonLayout.createSequentialGroup()
                        .addComponent(Vaschetta, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Tara1, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Stampa, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Cliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AddNewLine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        MonLayout.setVerticalGroup(
            MonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
            .addGroup(MonLayout.createSequentialGroup()
                .addComponent(Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddNewLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Vaschetta, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Stampa, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tara1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jTabbedPane1.addTab("tab1", Mon);

        javax.swing.GroupLayout TueLayout = new javax.swing.GroupLayout(Tue);
        Tue.setLayout(TueLayout);
        TueLayout.setHorizontalGroup(
            TueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 932, Short.MAX_VALUE)
        );
        TueLayout.setVerticalGroup(
            TueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 541, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab1", Tue);

        javax.swing.GroupLayout WedLayout = new javax.swing.GroupLayout(Wed);
        Wed.setLayout(WedLayout);
        WedLayout.setHorizontalGroup(
            WedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 932, Short.MAX_VALUE)
        );
        WedLayout.setVerticalGroup(
            WedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 541, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab1", Wed);

        javax.swing.GroupLayout ThuLayout = new javax.swing.GroupLayout(Thu);
        Thu.setLayout(ThuLayout);
        ThuLayout.setHorizontalGroup(
            ThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 932, Short.MAX_VALUE)
        );
        ThuLayout.setVerticalGroup(
            ThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 541, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab1", Thu);

        javax.swing.GroupLayout FriLayout = new javax.swing.GroupLayout(Fri);
        Fri.setLayout(FriLayout);
        FriLayout.setHorizontalGroup(
            FriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 932, Short.MAX_VALUE)
        );
        FriLayout.setVerticalGroup(
            FriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 541, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab1", Fri);

        javax.swing.GroupLayout SatLayout = new javax.swing.GroupLayout(Sat);
        Sat.setLayout(SatLayout);
        SatLayout.setHorizontalGroup(
            SatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 932, Short.MAX_VALUE)
        );
        SatLayout.setVerticalGroup(
            SatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 541, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab1", Sat);

        javax.swing.GroupLayout SunLayout = new javax.swing.GroupLayout(Sun);
        Sun.setLayout(SunLayout);
        SunLayout.setHorizontalGroup(
            SunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 932, Short.MAX_VALUE)
        );
        SunLayout.setVerticalGroup(
            SunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 541, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab1", Sun);

        jToolBar1.setRollover(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Enviroments");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LineOrderClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LineOrderClick
        if(!pressed)
            toConsole(evt);
    }//GEN-LAST:event_LineOrderClick

    private void StampaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StampaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StampaActionPerformed

    private void VaschettaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VaschettaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VaschettaActionPerformed

    private void Tara1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tara1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tara1ActionPerformed

    private void LineOrderPressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LineOrderPressed
        toConsole(evt);
        pressed=true;
    }//GEN-LAST:event_LineOrderPressed

    private void LineOrderReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LineOrderReleased
        if(pressed)
            toConsole(evt);
        pressed=false;
    }//GEN-LAST:event_LineOrderReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddNewLine;
    private javax.swing.JPanel Cliente;
    private javax.swing.JPanel Fri;
    private javax.swing.JPanel Mon;
    private javax.swing.JPanel Sat;
    private javax.swing.JPanel Settimana;
    private javax.swing.JButton Stampa;
    private javax.swing.JPanel Sun;
    private javax.swing.JButton Tara1;
    private javax.swing.JPanel Thu;
    private javax.swing.JPanel Tue;
    private javax.swing.JButton Vaschetta;
    private javax.swing.JPanel Wed;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        this.setVisible(true);        
    }
    private void toConsole(Object obj){
        String mes="";
        mes+=Calendar.HOUR_OF_DAY+":"+Calendar.MINUTE+":"+Calendar.SECOND;
        mes=mes+" > ";
        try{
            switch(obj.getClass().getName()){
                case "java.awt.event.MouseEvent":
                    mes=mes+"[MouseEvent]";                    
                    break;
                default:
                    mes=mes+"[D]";
                    break;
            }
           if(pressed)
               mes+="Premuto e non click";
        System.out.println(mes);
        }
        catch(Exception e){
            mes+=e.toString();
            System.out.println(mes+"\t"+obj.toString());
        }
    }
}