/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bollettario;

import static bollettario.Bollettario.debug;
import bollettario.FolderDataBase.ElencoPesate;
import bollettario.FolderDataBase.PrototipoPesata;
import bollettario.FolderDataBase.Prodotto;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.SwingConstants;

/**
 *
 * @author DiegoCarlo
 */
public class JFEliminaPesata extends javax.swing.JFrame {

    /**
     * Creates new form EliminaPesata
     */
    private ArrayList<Long> elencoJListPesate;
    private Font font;
    private long idOrdine;
    public JFEliminaPesata(long idOrdine, Font font)
    {
        if(debug)System.out.println("JFEliminaPesata.JFEliminaPesata()");
        this.font = font;
        this.idOrdine = idOrdine;
        initComponents();
        
        aggiornaJList();
    }
    public void aggiornaJList()
    {
        if(debug)System.out.println("JFEliminaPesata.aggiornaJList()");
        elencoJListPesate = Bollettario.interfaccia.interfPesate.getPesate();
        final String[] testoLista = new String[elencoJListPesate.size()];
        for(int i=0; i<elencoJListPesate.size(); i++)
        {
            Long idPesata = elencoJListPesate.get(i);
            PrototipoPesata pe = Bollettario.dataBase.getPesata(idPesata);
            Prodotto pr = Bollettario.dataBase.elencoProdotti.get(pe.idProdotto);
            
            String nome = pr.nome;
            testoLista[i] = idPesata + "| " + nome;
        }
        jList1.setModel(new javax.swing.AbstractListModel() {
        String[] strings = testoLista;
        public int getSize() { return strings.length; }
        public Object getElementAt(int i) { return strings[i]; }
        });
        verificaCorrettezza();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jLabelProdotto = new javax.swing.JLabel();
        jButtonReset = new javax.swing.JButton();
        jButtonAggiungi = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setTitle("Elimina Pesata");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jList1.setFont(font);
        jScrollPane1.setViewportView(jList1);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pesata", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 18))); // NOI18N

        jLabelProdotto.setText("jLabel1");
        jLabelProdotto.setFont(font);
        jLabelProdotto.setHorizontalAlignment(SwingConstants.CENTER);

        jButtonReset.setText("Annulla");
        jButtonReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonResetMouseClicked(evt);
            }
        });
        jButtonReset.setFont(font);

        jButtonAggiungi.setText("Elimina");
        jButtonAggiungi.setFont(font);
        jButtonAggiungi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonAggiungiMousePressed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelProdotto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonReset, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonAggiungi, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabelProdotto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonAggiungi, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(jButtonReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        if(debug)System.out.println("JFEliminaPesata.jList1ValueChanged()");
        int i = jList1.getSelectedIndex();
        if(i >= 0 && i < elencoJListPesate.size())
        {
            PrototipoPesata pe = Bollettario.dataBase.getPesata(elencoJListPesate.get(i));
            Prodotto pr = Bollettario.dataBase.getProdotto(pe.idProdotto);
            String nome = pr.nome;
            jLabelProdotto.setText(nome);
        }
        verificaCorrettezza();
    }//GEN-LAST:event_jList1ValueChanged

    private void jButtonResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonResetMouseClicked
        if(debug)System.out.println("JFEliminaPesata.jButtonResetMouseClicked()");
        annulla();
    }//GEN-LAST:event_jButtonResetMouseClicked
    private void annulla()
    {
        if(debug)System.out.println("JFEliminaPesata.annulla()");
        jList1.setSelectedIndex(-1);
        
    }
    private void jButtonAggiungiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAggiungiMousePressed
        if(debug)System.out.println("JFEliminaPesata.jButtonAggiungiMousePressed()");
        if(jButtonAggiungi.isEnabled())
        {
            int i = jList1.getSelectedIndex();
            Bollettario.dataBase.elencoPesate.remove(elencoJListPesate.get(i));
            Bollettario.salva();
            this.setVisible(false);
            Bollettario.interfaccia.aggiorna();
        }
    }//GEN-LAST:event_jButtonAggiungiMousePressed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if(debug)System.out.println("JFEliminaPesata.formWindowClosing()");
        Bollettario.interfaccia.setEnabled(true);
    }//GEN-LAST:event_formWindowClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAggiungi;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JLabel jLabelProdotto;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

    private void verificaCorrettezza()
    {
        if(debug)System.out.println("JFEliminaPesata.verificaCorrettezza()");
        int i = jList1.getSelectedIndex();
        if(i >= 0 && i < elencoJListPesate.size())
        {
            jButtonAggiungi.setEnabled(true);
        }
        else
        {
            jButtonAggiungi.setEnabled(false);
        }
    }
}
